---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Cochiko.
--- DateTime: 11/13/2022 12:51 PM
---

local helper = {}

function helper.HexToRGB(hex)
    return tonumber(hex:sub(1,2), 16)/255, tonumber(hex:sub(3,4), 16)/255, tonumber(hex:sub(5,6), 16)/255, 1;
end

AnimationHelper = helper
