---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Cochiko.
--- DateTime: 11/13/2022 12:20 PM
---

local helper = {}

function helper.IsPetOrGuardianEvent(sourceFlags)
    return (bit.band(sourceFlags, COMBATLOG_OBJECT_TYPE_GUARDIAN) > 0 or bit.band(sourceFlags, COMBATLOG_OBJECT_TYPE_PET) > 0)
            and bit.band(sourceFlags, COMBATLOG_OBJECT_AFFILIATION_MINE) > 0
end

function helper.IsDamageEvent(clue)
    return string.find(clue, "_DAMAGE")
end

function helper.IsMeleeEvent(clue)
    return string.find(clue, "SWING")
end

function helper.IsEnvironmentalEvent(clue)
    return string.find(clue, "ENVIRONMENTAL")
end

function helper.IsMissEvent(clue)
    return string.find(clue, "_MISSED")
end

function helper.IsAutoAttackSpell(spellName)
    return spellName == "melee" or spellName == "pet"
end

CombatLogHelper = helper
