---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Cochiko.
--- DateTime: 11/13/2022 4:08 PM
---

local levels = {
    INFO = 1,
    DEBUG = 2,
}
local helper = {
    LogLevels = levels,
}
local getLogLevel

function helper.Debug(msg)
    local level = getLogLevel and tonumber(getLogLevel())
    if level and level >= levels.DEBUG then
        print("DEBUG  "..msg)
    end
end

function helper.Info(msg)
    local level = getLogLevel and tonumber(getLogLevel())
    if level and level >= levels.INFO then
        print(msg)
    end
end

function GetDebugHelper(getLogLevelFn)
    getLogLevel = function()
        local level = getLogLevelFn and tonumber(getLogLevelFn())
        return level or levels.INFO
    end
    return helper
end
