---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Cochiko.
--- DateTime: 11/18/2022 1:30 PM
---


---@class TSUState
---@field changed boolean Informs WeakAuras that the states values have changed. Always set this to true for states that were changed.
---@field show boolean Controls whether the display is visible. Note, that states that have show set to false are automatically removed.
---@field name string The name, returned by %n
---@field icon number | string IconID or TexturePath, used in icons and progress bars
---@field texture number | string IconID or TexturePath, used in textures
---@field stacks number The stack count, returned by %s
---@field index number | string Sets the order the output will display in a dynamic group (if sorting is set to "none" on the group).
---Strings or numbers are fine but DO NOT MIX TYPES!
---
---@field progressType string Possible values: "timed" or "static"
---@field expirationTime number For "timed" progress type only; value should be relative to GetTime().
---@field duration number For "timed" progress type only; total duration of the bar in seconds. For example, a simple 5 second timer
---would use duration = 5 and expirationTime = GetTime() + 5
---@field paused boolean Set to true (and set a remaining value) to pause a "timed" progress. Set to false
---(and recalculate the expirationTime value) to resume.
---@field remaining number Only used with paused, gives WA the info needed to show paused progress at the current point.
---A quick example of using paused: https://wago.io/TSU-paused-example
---
---@field value number For "static" progress type only; arbitrary number between 0 and the given "total" (?).
---@field total number For "static" progress type only; arbitrary number used representing the maximum "value" (?).
---
---@field autoHide boolean Set to true to make the display automatically hide at the end of the "timed" progress. autoHide can also
---be used along with the "static" progressType by defining a duration and expirationTime along with the static value and total.
---While the static values will be displayed, the timed values will set the Hide time for the clone.
---@field additionalProgress table<TSUAdditionalProgress> This is a more complex field than the others but allows you to create "Overlays"
---on bars that you make using TSU.
local TSUState = {};


---@class TSUAdditionalProgress Allows you to create "Overlays" on bars that you make using TSU.
---@field min number Use with "max". Defines the left point of the overlay on the bar, and should be relative to the main bar's
---total/duration
---@field max number Use with "min". Defines the right point of the overlay on the bar, and should be relative to the main bar's
---total/duration
---
---@field direction string Use with "width" and (optionally) "offset". Defines the position of the Overlay relative to the moving edge
---of the bar.
---Should be either "forward" or "backward", dictating whether the Overlay will go ahead or behind the moving edge.
---@field width number Use with "direction" and (optionally) "offset". Defines the position of the Overlay relative to the moving edge
---of the bar, and is relative to the total/duration.
---@field offset number Optional. Use with "direction" and "width". Defines a simple offset from the bar's moving edge.
local TSUAdditionalProgress = {};
